[build]
  # ignore = "exit 0" # disable build on commit push
  base = "/"
  publish = "dist"
  command = "pnpm run build"
  environment = { NODE_VERSION = "20.11.0" }

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      font-src 'self';
      connect-src 'self';
      img-src 'self' https://openseadragon.github.io https://dzi-bucket.duclonghoang.com https://s3.cl2.du.cesnet.cz;
      media-src blob:;
      frame-src 'self' blob:;
      object-src 'none';
    '''
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(self)"
