backend:
  name: gitlab
  repo: duc-long-hoang/templates/astro
  branch: master
  base_url: https://sveltia-cms-auth.duclonghoang.com
  commit_messages:
    create: '[Sveltia CMS] Create {{collection}} "{{slug}}"'
    update: '[Sveltia CMS] Update {{collection}} "{{slug}}"'
    delete: '[Sveltia CMS] Delete {{collection}} "{{slug}}"'
    uploadMedia: '[Sveltia CMS] Upload "{{path}}"'
    deleteMedia: '[Sveltia CMS] Delete "{{path}}"'
    openAuthoring: '[Sveltia CMS] "{{message}}"'

locale: cs
site_domain: astro.duclonghoang.com
site_url: https://astro.duclonghoang.com
display_url: https://astro.duclonghoang.com
local_backend: true
media_folder: src/images/uploads
public_folder: src/images/uploads

slug:
  encoding: ascii
  clean_accents: true

i18n:
  structure: multiple_folders
  locales: [cs, en, de]
  default_locale: cs
  canonical_slug:
    key: defaultLocaleVersion
    value: "cs/{{slug}}"

collections:
  - name: tag # Used in routes, e.g., /admin/#/collections/blog
    label: Kategorie # Used in the UI
    folder: src/content/category # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete documents in this collection
    summary: "Kategorie: {{title}}" # A field to display in the editor overview
    slug: "{{title | localize}}" # Filename template, e.g., YYYY-MM-DD-title.md
    i18n: true # Enable localization for this collection
    fields: # The fields for each document, usually in frontmatter
      - label: Kategorie
        name: title
        widget: string
        i18n: true
  - name: blog # Used in routes, e.g., /admin/#/collections/blog
    label: Blog # Used in the UI
    folder: src/content/blog # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete documents in this collection
    summary: "Článek: {{author}} - {{title}}" # A field to display in the editor overview
    slug: "{{title | localize}}" # Filename template, e.g., YYYY-MM-DD-title.md
    i18n: true # Enable localization for this collection
    fields: # The fields for each document, usually in frontmatter
      - label: Titulek
        name: title
        widget: string
        i18n: true
      - label: Datum vytvoření
        name: date
        widget: datetime
        i18n: duplicate
      - label: Obrázek
        name: image
        widget: image
        required: false
        i18n: duplicate
      - label: Popisek obrázku
        name: imageAlt
        widget: string
        required: false
        i18n: true
      - label: Krátký popis článku
        name: description
        widget: string
        i18n: true
      - label: Autor
        name: author
        widget: string
        i18n: duplicate
      - label: Kategorie
        name: tag
        widget: relation
        collection: tag
        value_field: title
        search_fields: [title]
        required: false
        i18n: true
      - label: Text článku
        name: body
        widget: markdown
        i18n: true
